### PR TITLE
Fold two `tensor.extract_slice` ops

### PR DESCRIPTION
**Pull request by adam-smnk**
Adds a new rewrite pattern to the transform CanonicalizeOp.
The pattern combines two `tensor.extract_slice` ops when one extract slice is an input to another one.

### CODE REVIEW

**Comment by adam-smnk** [comment]
Looks like slice folding negatively affects bufferization transform as extra `memref.copy` ops are injected. I'll need to have a closer look at the transform.

**Comment by adam-smnk** [comment]
Examples based on `transform-mlp.mlir` test case `@mlp_single_layer_fused_and_packed`

## Original output no folder
### Canonicalized - prebufferization
```
%1 = tensor.empty() : tensor<4x8x32x32xf32>
    %2 = linalgx.pack %arg0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %1 : (tensor<128x256xf32> tensor<4x8x32x32xf32>) -> tensor<4x8x32x32xf32>
    %3 = tensor.empty() : tensor<16x8x32x32xf32>
    %4 = linalgx.pack %arg1 outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %3 : (tensor<256x512xf32> tensor<16x8x32x32xf32>) -> tensor<16x8x32x32xf32>
    %5 = tensor.empty() : tensor<4x16x32x32xf32>
    %6 = linalgx.pack %0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %5 : (tensor<128x512xf32> tensor<4x16x32x32xf32>) -> tensor<4x16x32x32xf32>
    %7 = scf.for %arg4 = %c0 to %c4 step %c1 iter_args(%arg5 = %6) -> (tensor<4x16x32x32xf32>) {
      %extracted_slice = tensor.extract_slice %2[%arg4, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<4x8x32x32xf32> to tensor<1x8x32x32xf32>
      %extracted_slice_0 = tensor.extract_slice %extracted_slice[0, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<1x8x32x32xf32> to tensor<8x32x32xf32>
      %9 = scf.for %arg6 = %c0 to %c16 step %c1 iter_args(%arg7 = %arg5) -> (tensor<4x16x32x32xf32>) {
        %extracted_slice_1 = tensor.extract_slice %4[%arg6, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<16x8x32x32xf32> to tensor<1x8x32x32xf32>
        %extracted_slice_2 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<4x16x32x32xf32> to tensor<1x1x32x32xf32>
        %extracted_slice_3 = tensor.extract_slice %extracted_slice_1[0, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<1x8x32x32xf32> to tensor<8x32x32xf32>
        %extracted_slice_4 = tensor.extract_slice %extracted_slice_2[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<1x1x32x32xf32> to tensor<32x32xf32>
        %10 = linalg.batch_reduce_matmul ins(%extracted_slice_0, %extracted_slice_3 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_4 : tensor<32x32xf32>) -> tensor<32x32xf32>
        %inserted_slice = tensor.insert_slice %10 into %extracted_slice_2[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<32x32xf32> into tensor<1x1x32x32xf32>
        %11 = linalg.generic {indxing_maps = [#map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"], library_call = "tpp.relu"} outs(%inserted_slice : tensor<1x1x32x32xf32>) {
```
 => `%extracted_slice_0`, `%extracted_slice_3`, and `%extracted_slice_4` could be removed

### Bufferized
```
%alloc = memref.alloc() {alignment = 128 : i64} : memref<4x8x32x32xf32>
    linalgx.pack %arg0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %alloc : (memref<128x256xf32, strided<[?, ?], offset: ?>> memref<4x8x32x32xf32>)
    %alloc_0 = memref.alloc() {alignment = 128 : i64} : memref<16x8x32x32xf32>
    linalgx.pack %arg1 outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %alloc_0 : (memref<256x512xf32, strided<[?, ?], offset: ?>> memref<16x8x32x32xf32>)
    %alloc_1 = memref.alloc() {alignment = 128 : i64} : memref<4x16x32x32xf32>
    linalgx.pack %arg3 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %alloc_1 : (memref<128x512xf32, strided<[?, ?], offset: ?>> memref<4x16x32x32xf32>)
    scf.for %arg4 = %c0 to %c4 step %c1 {
      %subview = memref.subview %alloc[%arg4, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : memref<4x8x32x32xf32> to memref<1x8x32x32xf32, strided<[8192, 1024, 32, 1], offset: ?>>
      %subview_2 = memref.subview %subview[0, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : memref<1x8x32x32xf32, strided<[8192, 1024, 32, 1], offset: ?>> to memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>
      scf.for %arg5 = %c0 to %c16 step %c1 {
        %subview_3 = memref.subview %alloc_0[%arg5, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : memref<16x8x32x32xf32> to memref<1x8x32x32xf32, strided<[8192, 1024, 32, 1], offset: ?>>
        %subview_4 = memref.subview %alloc_1[%arg4, %arg5, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : memref<4x16x32x32xf32> to memref<1x1x32x32xf32, strided<[16384, 1024, 32, 1], offset: ?>>
        %subview_5 = memref.subview %subview_3[0, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : memref<1x8x32x32xf32, strided<[8192, 1024, 32, 1], offset: ?>> to memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>
        %subview_6 = memref.subview %subview_4[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : memref<1x1x32x32xf32, strided<[16384, 1024, 32, 1], offset: ?>> to memref<32x32xf32, strided<[32, 1], offset: ?>>
        linalg.batch_reduce_matmul ins(%subview_2, %subview_5 : memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>, memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>) outs(%subview_6 : memref<32x32xf32, strided<[32, 1], offset: ?>>)
        linalg.generic {indexing_maps = [#map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"], library_call = "tpp.relu"} outs(%subview_4 : memref<1x1x32x32xf32, strided<[16384, 1024, 32, 1], offset: ?>>) {
```

=> direct bufferization with no extra buffers

## Output with extra folder added to `CanonicalizeOp`
### Canonicalized - prebufferization
```
 %1 = tensor.empty() : tensor<4x8x32x32xf32>
    %2 = linalgx.pack %arg0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %1 : (tensor<128x256xf32> tensor<4x8x32x32xf32>) -> tensor<4x8x32x32xf32>
    %3 = tensor.empty() : tensor<16x8x32x32xf32>
    %4 = linalgx.pack %arg1 outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %3 : (tensor<256x512xf32> tensor<16x8x32x32xf32>) -> tensor<16x8x32x32xf32>
    %5 = tensor.empty() : tensor<4x16x32x32xf32>
    %6 = linalgx.pack %0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %5 : (tensor<128x512xf32> tensor<4x16x32x32xf32>) -> tensor<4x16x32x32xf32>
    %7 = scf.for %arg4 = %c0 to %c4 step %c1 iter_args(%arg5 = %6) -> (tensor<4x16x32x32xf32>) {
      %extracted_slice = tensor.extract_slice %2[%arg4, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<4x8x32x32xf32> to tensor<8x32x32xf32>
      %9 = scf.for %arg6 = %c0 to %c16 step %c1 iter_args(%arg7 = %arg5) -> (tensor<4x16x32x32xf32>) {
        %extracted_slice_0 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<4x16x32x32xf32> to tensor<1x1x32x32xf32>
        %extracted_slice_1 = tensor.extract_slice %4[%arg6, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<16x8x32x32xf32> to tensor<8x32x32xf32>
        %extracted_slice_2 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<4x16x32x32xf32> to tensor<32x32xf32>
        %10 = linalg.batch_reduce_matmul ins(%extracted_slice, %extracted_slice_1 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_2 : tensor<32x32xf32>) -> tensor<32x32xf32>
        %inserted_slice = tensor.insert_slice %10 into %extracted_slice_0[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<32x32xf32> into tensor<1x1x32x32xf32>
        %11 = linalg.generic {indexing_maps = [#map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"], library_call = "tpp.relu"} outs(%inserted_slice : tensor<1x1x32x32xf32>) {
```

=> slices of slices removed

### Bufferized
```
 %alloc = memref.alloc() {alignment = 128 : i64} : memref<4x8x32x32xf32>
    linalgx.pack %arg0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %alloc : (memref<128x256xf32, strided<[?, ?], offset: ?>> memref<4x8x32x32xf32>)
    %alloc_0 = memref.alloc() {alignment = 128 : i64} : memref<16x8x32x32xf32>
    linalgx.pack %arg1 outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %alloc_0 : (memref<256x512xf32, strided<[?, ?], offset: ?>> memref<16x8x32x32xf32>)
    %alloc_1 = memref.alloc() {alignment = 128 : i64} : memref<4x16x32x32xf32>
    linalgx.pack %arg3 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %alloc_1 : (memref<128x512xf32, strided<[?, ?], offset: ?>> memref<4x16x32x32xf32>)
    scf.for %arg4 = %c0 to %c4 step %c1 {
      %subview = memref.subview %alloc[%arg4, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : memref<4x8x32x32xf32> to memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>
      scf.for %arg5 = %c0 to %c16 step %c1 {
        %subview_2 = memref.subview %alloc_1[%arg4, %arg5, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : memref<4x16x32x32xf32> to memref<1x1x32x32xf32, strided<[16384, 1024, 32, 1], offset: ?>>
        %alloc_3 = memref.alloc() {alignment = 128 : i64} : memref<1x1x32x32xf32>
        memref.copy %subview_2, %alloc_3 : memref<1x1x32x32xf32, strided<[16384, 1024, 32, 1], offset: ?>> to memref<1x1x32x32xf32>
        %subview_4 = memref.subview %alloc_0[%arg5, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : memref<16x8x32x32xf32> to memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>
        %subview_5 = memref.subview %alloc_1[%arg4, %arg5, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : memref<4x16x32x32xf32> to memref<32x32xf32, strided<[32, 1], offset: ?>>
        linalg.batch_reduce_matmul ins(%subview, %subview_4 : memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>, memref<8x32x32xf32, strided<[1024, 32, 1], offset: ?>>) outs(%subview_5 : memref<32x32xf32, strided<[32, 1], offset: ?>>)
        %subview_6 = memref.subview %alloc_3[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : memref<1x1x32x32xf32> to memref<32x32xf32, strided<[32, 1]>>
        memref.copy %subview_5, %subview_6 : memref<32x32xf32, strided<[32, 1], offset: ?>> to memref<32x32xf32, strided<[32, 1]>>
        linalg.generic {indexing_maps = [#map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"], library_call = "tpp.relu"} outs(%alloc_3 : memref<1x1x32x32xf32>) {
```

=> extra `%alloc_3 = memref.alloc()` in the inner loop

### Bufferization conflict analysis debug data
```
%1 = tensor.empty() : tensor<4x8x32x32xf32>
    %2 = linalgx.pack {__inplace_operands_attr__ = ["true", "false"]} %arg0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %1 : (tensor<128x256xf32> tensor<4x8x32x32xf32>) -> tensor<4x8x32x32xf32>
    %3 = tensor.empty() : tensor<16x8x32x32xf32>
    %4 = linalgx.pack {__inplace_operands_attr__ = ["true", "false"]} %arg1 outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %3 : (tensor<256x512xf32> tensor<16x8x32x32xf32>) -> tensor<16x8x32x32xf32>
    %5 = tensor.empty() : tensor<4x16x32x32xf32>
    %6 = linalgx.pack {__inplace_operands_attr__ = ["true", "false"]} %0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %5 : (tensor<128x512xf32> tensor<4x16x32x32xf32>) -> tensor<4x16x32x32xf32>
    %7 = scf.for %arg4 = %c0 to %c4 step %c1 iter_args(%arg5 = %6) -> (tensor<4x16x32x32xf32>) {
      %extracted_slice = tensor.extract_slice %2[%arg4, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] {__inplace_operands_attr__ = ["true", "none"]} : tensor<4x8x32x32xf32> to tensor<8x32x32xf32>
      %9 = scf.for %arg6 = %c0 to %c16 step %c1 iter_args(%arg7 = %arg5) -> (tensor<4x16x32x32xf32>) {
        %extracted_slice_0 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] {__inplace_operands_attr__ = ["false", "none", "none"]} : tensor<4x16x32x32xf32> to tensor<1x1x32x32xf32>
        %extracted_slice_1 = tensor.extract_slice %4[%arg6, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] {__inplace_operands_attr__ = ["true", "none"]} : tensor<16x8x32x32xf32> to tensor<8x32x32xf32>
        %extracted_slice_2 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] {__inplace_operands_attr__ = ["true", "none", "none"]} : tensor<4x16x32x32xf32> to tensor<32x32xf32>
        %10 = linalg.batch_reduce_matmul {"C_0[CONFL-WRITE: 2]", __inplace_operands_attr__ = ["true", "true", "true"]} ins(%extracted_slice, %extracted_slice_1 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_2 : tensor<32x32xf32>) -> tensor<32x32xf32>
        %inserted_slice = tensor.insert_slice %10 into %extracted_slice_0[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] {"C_0[READ: 1]", __inplace_operands_attr__ = ["true", "true"]} : tensor<32x32xf32> into tensor<1x1x32x32xf32>
        %11 = linalg.generic {indexing_maps = [#map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"], library_call = "tpp.relu"} outs(%inserted_slice : tensor<1x1x32x32xf32>) attrs =  {__inplace_operands_attr__ = ["true"]} {
```

=> conflict in `%10 = linalg.batch_reduce_matmul` - write to `%extracted_slice_2` which maps to rank reduced slice of `%arg7`
=> conflict in `%inserted_slice = tensor.insert_slice` - read of `%extracted_slice_0` which maps to slice of `%arg7`

**Comment by chelini** [comment]
Ok I may have an intuition. Can you try to add `%4` as iter_args in both loops?

**Comment by adam-smnk** [comment]
No difference, unfortunately.

My test input:
```
// RUN: tpp-opt %s -transform-dialect-interpreter -transform-drop-schedule -loop-invariant-code-motion -canonicalize -cse -canonicalize -split-input-file | FileCheck %s

transform.sequence failures(propagate) {
  ^bb0(%arg1: !pdl.operation):
    %7 = transform.structured.match ops{["func.func"]} in %arg1
    transform.structured.canonicalize %7

    transform.bufferization.one_shot_bufferize %arg1 {
        target_is_module = true,
        bufferize_function_boundaries = true }
}

#map = affine_map<(d0, d1) -> (d1)>
#map1 = affine_map<(d0, d1) -> (d0, d1)>
#map2 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
module {
  func.func @mlp_single_layer_fused_and_packed(%arg0: tensor<128x256xf32>, %arg1: tensor<256x512xf32>, %arg2: tensor<512xf32>, %arg3: tensor<128x512xf32>) -> tensor<128x512xf32> {
    %c16 = arith.constant 16 : index
    %c4 = arith.constant 4 : index
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %cst = arith.constant 0.000000e+00 : f32
    %0 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel"], library_call = "tpp.identity"} ins(%arg2 : tensor<512xf32>) outs(%arg3 : tensor<128x512xf32>) {
    ^bb0(%in: f32, %out: f32):
      linalg.yield %in : f32
    } -> tensor<128x512xf32>
    %1 = tensor.empty() : tensor<4x8x32x32xf32>
    %2 = linalgx.pack %arg0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %1 : (tensor<128x256xf32> tensor<4x8x32x32xf32>) -> tensor<4x8x32x32xf32>
    %3 = tensor.empty() : tensor<16x8x32x32xf32>
    %4 = linalgx.pack %arg1 outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %3 : (tensor<256x512xf32> tensor<16x8x32x32xf32>) -> tensor<16x8x32x32xf32>
    %5 = tensor.empty() : tensor<4x16x32x32xf32>
    %6 = linalgx.pack %0 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %5 : (tensor<128x512xf32> tensor<4x16x32x32xf32>) -> tensor<4x16x32x32xf32>
    %7, %20 = scf.for %arg4 = %c0 to %c4 step %c1 iter_args(%arg5 = %6, %arg10 = %4) -> (tensor<4x16x32x32xf32>, tensor<16x8x32x32xf32>) {
      %extracted_slice = tensor.extract_slice %2[%arg4, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<4x8x32x32xf32> to tensor<1x8x32x32xf32>
      %extracted_slice_0 = tensor.extract_slice %extracted_slice[0, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<1x8x32x32xf32> to tensor<8x32x32xf32>
      %9, %21 = scf.for %arg6 = %c0 to %c16 step %c1 iter_args(%arg7 = %arg5, %arg11 = %arg10) -> (tensor<4x16x32x32xf32>, tensor<16x8x32x32xf32>) {
        %extracted_slice_1 = tensor.extract_slice %arg11[%arg6, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<16x8x32x32xf32> to tensor<1x8x32x32xf32>
        %extracted_slice_2 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<4x16x32x32xf32> to tensor<1x1x32x32xf32>
        %extracted_slice_3 = tensor.extract_slice %extracted_slice_1[0, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<1x8x32x32xf32> to tensor<8x32x32xf32>
        %extracted_slice_4 = tensor.extract_slice %extracted_slice_2[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<1x1x32x32xf32> to tensor<32x32xf32>
        %10 = linalg.batch_reduce_matmul ins(%extracted_slice_0, %extracted_slice_3 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_4 : tensor<32x32xf32>) -> tensor<32x32xf32>
        %inserted_slice = tensor.insert_slice %10 into %extracted_slice_2[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<32x32xf32> into tensor<1x1x32x32xf32>
        %11 = linalg.generic {indexing_maps = [#map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"], library_call = "tpp.relu"} outs(%inserted_slice : tensor<1x1x32x32xf32>) {
        ^bb0(%out: f32):
          %12 = arith.maxf %out, %cst : f32
          linalg.yield %12 : f32
        } -> tensor<1x1x32x32xf32>
        %inserted_slice_5 = tensor.insert_slice %11 into %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<1x1x32x32xf32> into tensor<4x16x32x32xf32>
        scf.yield %inserted_slice_5, %arg11 : tensor<4x16x32x32xf32>, tensor<16x8x32x32xf32>
      }
      scf.yield %9, %21 : tensor<4x16x32x32xf32>, tensor<16x8x32x32xf32>
    }
    %8 = linalgx.unpack %7 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %0 : (tensor<4x16x32x32xf32> tensor<128x512xf32>) -> tensor<128x512xf32>
    return %8 : tensor<128x512xf32>
  }
}
```

**Comment by chelini** [comment]
I think all the operands for the brgemm should come from iter args.

**Comment by adam-smnk** [comment]
Moving everything into iter_args didn't help but it looks like the extra iter_args get dropped before bufferization by canonicalization pass. The bufforization conflict analysis still find RaW after tensor slice folding.
I tried following OneShotAnalysis `hasReadAfterWriteInterference` and on its own it looks rather okay. However, bufferization support logic is a bit limited throughout different places/dialects (e.g., `isMemoryWrite` helper functions) so perhaps this would have to be addressed in a different place.

### Without slice folder
The conflict analysis resolves as:
```
- check conflict:
  uRead = operand 1 of mlir-asm-printer: Verifying operation: func.func
%inserted_slice = tensor.insert_slice %10 into %extracted_slice_2[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<32x32xf32> into tensor<1x1x32x32xf32>
  unConflictingWrite = operand 2 of mlir-asm-printer: Verifying operation: func.func
%10 = linalg.batch_reduce_matmul ins(%extracted_slice_0, %extracted_slice_3 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_4 : tensor<32x32xf32>) -> tensor<32x32xf32>
  no conflict: op interace of reading op says 'no'
```
for the following IR:
```
%9 = scf.for %arg6 = %c0 to %c16 step %c1 iter_args(%arg7 = %arg5) -> (tensor<4x16x32x32xf32>) {
  %extracted_slice_1 = tensor.extract_slice %4[%arg6, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<16x8x32x32xf32> to tensor<1x8x32x32xf32>
  %extracted_slice_2 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<4x16x32x32xf32> to tensor<1x1x32x32xf32>
  %extracted_slice_3 = tensor.extract_slice %extracted_slice_1[0, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<1x8x32x32xf32> to tensor<8x32x32xf32>
  %extracted_slice_4 = tensor.extract_slice %extracted_slice_2[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<1x1x32x32xf32> to tensor<32x32xf32>
  %10 = linalg.batch_reduce_matmul ins(%extracted_slice_0, %extracted_slice_3 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_4 : tensor<32x32xf32>) -> tensor<32x32xf32>
  %inserted_slice = tensor.insert_slice %10 into %extracted_slice_2[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<32x32xf32> into tensor<1x1x32x32xf32>
```

### With slice folder
The conflict analysis resolves as:
```
- check conflict:
  uRead = operand 1 of mlir-asm-printer: Verifying operation: func.func
%inserted_slice = tensor.insert_slice %10 into %extracted_slice_0[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<32x32xf32> into tensor<1x1x32x32xf32>
  unConflictingWrite = operand 2 of mlir-asm-printer: Verifying operation: func.func
%10 = linalg.batch_reduce_matmul ins(%extracted_slice, %extracted_slice_1 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_2 : tensor<32x32xf32>) -> tensor<32x32xf32>
  * lastWrite = <block argument> of type 'tensor<4x16x32x32xf32>' at index: 1
  => RaW CONFLICT FOUND
```
for the following IR:
```
%9 = scf.for %arg6 = %c0 to %c16 step %c1 iter_args(%arg7 = %arg5) -> (tensor<4x16x32x32xf32>) {
  %extracted_slice_0 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<4x16x32x32xf32> to tensor<1x1x32x32xf32>
  %extracted_slice_1 = tensor.extract_slice %4[%arg6, 0, 0, 0] [1, 8, 32, 32] [1, 1, 1, 1] : tensor<16x8x32x32xf32> to tensor<8x32x32xf32>
  %extracted_slice_2 = tensor.extract_slice %arg7[%arg4, %arg6, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<4x16x32x32xf32> to tensor<32x32xf32>
  %10 = linalg.batch_reduce_matmul ins(%extracted_slice, %extracted_slice_1 : tensor<8x32x32xf32>, tensor<8x32x32xf32>) outs(%extracted_slice_2 : tensor<32x32xf32>) -> tensor<32x32xf32>
  %inserted_slice = tensor.insert_slice %10 into %extracted_slice_0[0, 0, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : tensor<32x32xf32> into tensor<1x1x32x32xf32>
```

I have a feeling that the existing analysis passes for `InsertSliceOp` simply fail to recognize that `%extracted_slice_0` and `%extracted_slice_2` alias the exact same memory location - `%extracted_slice_2` is a rank reduced version of `%extracted_slice_0`. Perhaps this could be amended by expanding `isNotConflictingInsertSliceLikeOp` pass in `BufferizableOpInterfaceImpl.cpp`.

**Comment by adam-smnk** [comment]
Anyway, I'll stop digging deeper for now.
As the tensor slice folding can impact bufferization negatively, it is added to `structured.canonicalize` transform as optional and can be enabled with a new `CanonicalizeOp` transform attribute `merge_tensor_slices`.
I also found out that a tensor slice folding rewrite pattern has already been upstreamed so our transform pass switched now uses these patterns that cover both extract and insert slice ops.

**Review by chelini — APPROVED** [review]
Ok for me. But maybe good to fix it upstream

**Pull request merged**
