### PR TITLE
Disable benchmarks

### PR DESCRIPTION
**Pull request by chelini**
After #158 we can re-enable them.

### CODE REVIEW

**Comment by adam-smnk** [comment]
Did benchmarks start actively failing on CI or sth?

**Comment by chelini** [comment]
> Did benchmarks start actively failing on CI or sth?

Not on the CI, I think. If we want to keep checking this on the CI I can have this change locally.

**Comment by rengolin** [comment]
Isn't this a problem only when using GCC?

**Review by rengolin — CHANGES_REQUESTED** [review]
Let's not disable tests just because they fail locally. We've been through this. We need to open issues, reproduce the CI locally and change/add build modes once we fix them. But removing tests like that goes against forward progress and we can't have that.

**Comment by chelini** [comment]
Ok. I will keep the change local.

**Pull request closed without merging**
