### PR TITLE
Add support for 1d/3d/4d memref

### PR DESCRIPTION
**Pull request by chelini**

### CODE REVIEW

**Review by rengolin — COMMENTED** [review]
accidental delete of `vec_2d_compare`, as broken in the test. Either keep `vec_Nd_compare` for all dimensions or rewrite the benchmark drivers to match (all three use it).

**Comment by chelini** [comment]
> 

We want to remove `*_compare` functions as we want to use libxsmm utils for that. I will check why it fails.

**Comment by rengolin** [comment]
It's because we use `vec_f2d_compare` directly on the benchmarks. All three drivers do that, we'd need to remove from them before merge.

**Review by rengolin — APPROVED** [review]
Once you make it work, it should be fine to keep it for experiments, even if we're going to use the `tpp-opt` soon.

**Comment by rengolin** [comment]
This will require rebase and probably re-work to fix the failing test. Do you want to keep this in a branch instead?

**Comment by chelini** [comment]
ok.

**Pull request closed without merging**
